# Form implementation generated from reading ui file 'AdminWindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 781, 521))
        font = QtGui.QFont()
        font.setFamily("Avenir")
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.usersTab = QtWidgets.QWidget()
        self.usersTab.setObjectName("usersTab")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.usersTab)
        self.tableWidget.setGeometry(QtCore.QRect(10, 0, 761, 221))
        font = QtGui.QFont()
        font.setFamily("Avenir")
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tabWidget.addTab(self.usersTab, "")
        self.productTab = QtWidgets.QWidget()
        self.productTab.setObjectName("productTab")
        self.tabWidget.addTab(self.productTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBackup = QtGui.QAction(parent=MainWindow)
        self.actionBackup.setObjectName("actionBackup")
        self.actionRestore = QtGui.QAction(parent=MainWindow)
        self.actionRestore.setObjectName("actionRestore")
        self.action_2 = QtGui.QAction(parent=MainWindow)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.actionBackup)
        self.menu.addAction(self.actionRestore)
        self.menu.addSeparator()
        self.menu.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.usersTab), _translate("MainWindow", "Пользователи"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.productTab), _translate("MainWindow", "Товары"))
        self.menu.setTitle(_translate("MainWindow", "База данных"))
        self.actionBackup.setText(_translate("MainWindow", "Backup"))
        self.actionRestore.setText(_translate("MainWindow", "Restore"))
        self.action_2.setText(_translate("MainWindow", "Выйти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())




